config:
  info: "master branch, springcloud-config/config-dev.yml version=1.2.1"
  jdbc-url: "jdbc:mysql://127.0.0.1:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC"
